version: 2

sources:
  - name: aw_postgres
    database: aw-from-nekt
    schema: raw
    tables:
      - name: humanresources_department
      - name: humanresources_employee
      - name: person_address
      - name: person_countryregion
      - name: person_stateprovince
      - name: production_product
      - name: production_productcategory
      - name: production_productsubcategory
      - name: sales_creditcard
      - name: sales_customer
      - name: sales_salesorderdetail
      - name: sales_salesorderheader
      - name: sales_salesperson
      - name: sales_salesreason
      - name: sales_salesterritory
      - name: sales_store
      - name: person_person