version: 2

sources:
  - name: aw_postgres
    database: aw-bigquery  
    schema: aw_postgres  
    tables:
      - name: address
      - name: countryregion
      - name: customer
      - name: employee
      - name: person
      - name: product
      - name: productproductphoto
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesperson
      - name: salesreason
      - name: specialofferproduct
      - name: stateprovince